Neos:
  Fusion:
    defaultContext:
      'Neos.GoogleAnalytics.TrackingConfiguration': 'Neos\GoogleAnalytics\Eel\Helper\TrackingConfiguration'
  Neos:
    fusion:
      autoInclude:
        'Neos.GoogleAnalytics': true

  GoogleAnalytics:
    # Default settings
    default:
      addToPagePrototype: true
      analytics:
        id: false
        parameters: # define additional GA paramters here e.g. IP anonymization
          # anonymize_ip: true
      tagManager:
        id: false

    # Site specific settings
    sites: []
      ## All site specific settings are indexed by site node name
      #
      # neosdemo:
      #   addToPagePrototype: false
      #   analytics:
      #     id: 'G-XXXXXXXXXX'
      #   tagManager:
      #     id: GTM-XXXXX
